load("//:proto_defs.bzl", "rust_protobuf_library")

rust_protobuf_library(
    name = "buck2bes_proto",
    srcs = glob(["src/**/*.rs"]),
    build_script = "build.rs",
    proto_srcs = "//proto:all",
    build_script_deps = [
        "//third-party:tonic-prost-build",
    ],
    deps = [
        "//third-party:prost",
        "//third-party:tonic",
        "//third-party:tonic-prost",
        "//third-party:serde",
    ],
    visibility = ["PUBLIC"]
)
